[package]
name = "bitrange"
version = "0.1.0"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
bitrange_macro = { path = "proc_macro" }
