[package]
name = "bitrange_plugin"
version = "0.1.1"
authors = ["Victor Koenders"]
description = "Compiler plugin for bitrange to parse formats"
license = "MIT"
readme = "../readme"

[lib]
name = "bitrange_plugin"
proc-macro = true
